"""Default ignore rules for Synapse scanning."""

from __future__ import annotations

# Directory names to always skip
IGNORED_DIRS: set[str] = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    ".venv",
    "venv",
    "env",
    ".env",
    "dist",
    "build",
    ".next",
    ".dart_tool",
    "target",
    "vendor",
    "coverage",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    ".eggs",
    "*.egg-info",
    ".idea",
    ".vscode",
    "__snapshots__",
    ".turbo",
    ".cache",
    "out",
}

# File extensions to skip (binaries, generated, huge)
IGNORED_EXTENSIONS: set[str] = {
    ".pyc", ".pyo", ".class", ".o", ".obj", ".dll", ".so", ".dylib",
    ".exe", ".bin", ".dat", ".db", ".sqlite", ".sqlite3",
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp",
    ".mp3", ".mp4", ".wav", ".avi", ".mov", ".mkv", ".flv",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".woff", ".woff2", ".ttf", ".eot",
    ".lock",
}

# File names to skip
IGNORED_FILENAMES: set[str] = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "composer.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "poetry.lock",
    ".DS_Store",
    "Thumbs.db",
}

# Project indicator files → project type mapping
PROJECT_INDICATORS: dict[str, str] = {
    ".git": "git",
    "package.json": "node",
    "pyproject.toml": "python",
    "requirements.txt": "python",
    "setup.py": "python",
    "setup.cfg": "python",
    "Pipfile": "python",
    "pubspec.yaml": "flutter",
    "Cargo.toml": "rust",
    "go.mod": "go",
    ".sln": "dotnet",
    "pom.xml": "java",
    "build.gradle": "java",
    "build.gradle.kts": "java",
    "Gemfile": "ruby",
    "Makefile": "c_cpp",
    "CMakeLists.txt": "c_cpp",
    "cabal.project": "haskell",
    "stack.yaml": "haskell",
}

# Extensions → language mapping
EXTENSION_LANGUAGE_MAP: dict[str, str] = {
    ".py": "Python",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".rs": "Rust",
    ".go": "Go",
    ".java": "Java",
    ".kt": "Kotlin",
    ".scala": "Scala",
    ".rb": "Ruby",
    ".c": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".h": "C/C++ Header",
    ".hpp": "C++ Header",
    ".cs": "C#",
    ".fs": "F#",
    ".swift": "Swift",
    ".dart": "Dart",
    ".lua": "Lua",
    ".php": "PHP",
    ".r": "R",
    ".R": "R",
    ".m": "Objective-C",
    ".mm": "Objective-C++",
    ".hs": "Haskell",
    ".elm": "Elm",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".erl": "Erlang",
    ".clj": "Clojure",
    ".cljs": "ClojureScript",
    ".zig": "Zig",
    ".nim": "Nim",
    ".v": "V",
    ".jl": "Julia",
    ".sql": "SQL",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".ps1": "PowerShell",
    ".bat": "Batch",
    ".cmd": "Batch",
    ".html": "HTML",
    ".htm": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".less": "Less",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".graphql": "GraphQL",
    ".gql": "GraphQL",
    ".proto": "Protocol Buffers",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".toml": "TOML",
    ".json": "JSON",
    ".xml": "XML",
    ".md": "Markdown",
    ".rst": "reStructuredText",
    ".dockerfile": "Dockerfile",
}

# Source code extensions (files worth parsing for symbols)
SOURCE_EXTENSIONS: set[str] = {
    ".py", ".js", ".jsx", ".ts", ".tsx",
    ".rs", ".go", ".java", ".kt", ".scala",
    ".rb", ".c", ".cpp", ".cc", ".cxx", ".h", ".hpp",
    ".cs", ".fs", ".swift", ".dart",
    ".lua", ".php", ".r", ".hs", ".elm",
    ".ex", ".exs", ".erl", ".clj", ".cljs",
    ".zig", ".nim", ".jl",
    ".vue", ".svelte",
}
